all:
	mkdir -p ./debug
	/home/lbogdanov/git_projects/STM32F769I-disco_Buildroot/buildroot/output/host/bin/arm-buildroot-uclinux-uclibcgnueabi-gcc firstmod_app.c -o ./debug/firstmod_app.bin
clean:
	rm -r ./debug
