all:
	mkdir -p ./debug
	/home/lbogdanov/git_projects/STM32F769I-disco_Buildroot/buildroot/output/host/bin/arm-buildroot-uclinux-uclibcgnueabi-gcc firstapp.c -o ./debug/firstapp.bin
clean:
	rm -r ./debug
